name: rms
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-rms
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nest-rms
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rms?schema=public
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin-rms
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db