apiVersion: v1
kind: Secret
metadata:
  name: rms-secrets
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=     
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cm1z              
