apiVersion: v1
kind: Secret
metadata:
  name: rms-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9ybXM/c2NoZW1hPXB1YmxpYw==
  MERCADO_PAGO_ACCESS_TOKEN: VEVTVC04Njc4MDM4MDAzOTUyNjIzLTA1MjcxOC1jZWM1MTczNjM1ZTVkZTM5MGQwNTg2Mzc4ZDUzM2ZlOS0xMDY4MTkzNzg=
