apiVersion: v1
kind: Secret
metadata:
  name: rms-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/rms?schema=public"
  MERCADO_PAGO_ACCESS_TOKEN: "TEST-8678038003952623-052718-cec5173635e5de390d0586378d533fe9-106819378"
