apiVersion: v1
kind: Service
metadata:
  name: rms-app-service
spec:
  selector:
    app: rms-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
  type: NodePort
